Fix : #100 show searched word in input
nakhll-company/nakhll_frontend pull request #109
Opened 2022-06-06 08:51 UTC by milad7212

بر اساس url اگه  کلمه ای داخل کوئری سرچ شده باشد . داخل اینپوت سرچ هم نمایش داده خواهد شد

2022-06-08 10:40 UTC, sahar-shafiee requested changes

2022-06-08 10:40 UTC, sahar-shafiee commented on components/shopLayout/header/header.jsx
> +                      <div style={{ position: 'absolute', top: '-12px', right: '-10px', cursor: 'pointer' }}
@milad7212 
لطفا از استایل اینلاین استفاده نکنید

2022-06-09 04:06 UTC, milad7212 commented on components/shopLayout/header/header.jsx
> +                      <div style={{ position: 'absolute', top: '-12px', right: '-10px', cursor: 'pointer' }}
@sahar-shafiee 
اصلاح شد.

2022-06-09 07:35 UTC, sahar-shafiee approved these changes

2022-06-09 07:36 UTC, merged