Fix : Bug #12 : delete image profile
nakhll-company/nakhll_frontend pull request #14
Opened 2022-05-14 03:57 UTC by milad7212

2022-05-14 06:55 UTC, likecodingloveproblems commented on containers/settings/components/topPictures/index.jsx
> +              <BsTrash size={25} color="red" />
Please use delete image API.
its path: {{host}}/api/v1/profile/images/{{image_id}}/

2022-05-14 06:57 UTC, likecodingloveproblems requested changes
@PouryaMansouri please help @milad7212 
@milad7212 said id is not defined!

2022-05-14 07:36 UTC, PouryaMansouri commented
> @PouryaMansouri please help @milad7212 @milad7212 said id is not defined!

The image can't be null in the database,
It should be changed with the default image, so it is not better to use the patch method to update the image with the default?

2022-05-21 06:14 UTC, milad7212 commented
درست شد این مورد

2022-05-21 10:50 UTC, likecodingloveproblems commented on containers/settings/components/topPictures/index.jsx
> +
please seperate this function in a file.

2022-05-29 08:46 UTC, sahar-shafiee requested changes

2022-05-29 08:46 UTC, sahar-shafiee commented on containers/settings/components/topPictures/index.jsx
> +import { base64Profile } from "../../../../public/icons/icon";
@milad7212 
چرا باید تو پابلیک یک فایل js باشه؟
دقیقا چه کاری انجام میده؟

2022-05-29 08:51 UTC, sahar-shafiee requested changes

2022-05-29 08:51 UTC, sahar-shafiee commented on containers/settings/components/topPictures/callApiDelete.js
> +import {
@milad7212 
لطفا فایل ای پی ای رو داخل پوشه ای پی ای قرار بدین

2022-05-29 09:09 UTC, milad7212 commented on containers/settings/components/topPictures/index.jsx
> +import { base64Profile } from "../../../../public/icons/icon";
عکس که فرمت بیس64 داره در ان قرار داره که برای حذف بجاب کال کردن ای پی ای فرستاده میشد سرور .که الان  با ای پی ای حذف میشه و نیاز به این مورد نیست

2022-05-29 09:19 UTC, sahar-shafiee approved these changes

2022-05-29 09:44 UTC, merged