Fix : #139
nakhll-company/nakhll_frontend pull request #147
Opened 2022-06-12 08:28 UTC by milad7212

2022-06-14 06:57 UTC, sahar-shafiee requested changes

2022-06-14 06:57 UTC, sahar-shafiee commented on redux/actions/cart/_reduceProduct.jsx
> +      if (count == 1) {
بهتر است از سه مساوی استفاده کنید

2022-06-15 10:05 UTC, sahar-shafiee requested changes

2022-06-15 10:05 UTC, sahar-shafiee commented on redux/actions/cart/_reduceProduct.jsx
> +      if (count == 1) {
@milad7212 بی زحمت این پول ریکوئست رو تصحیح کنید

2022-06-16 04:38 UTC, milad7212 commented on redux/actions/cart/_reduceProduct.jsx
> +      if (count == 1) {
تفاوت انچنانی نداره در اینجا دو مساوی هم خطایی ایجاد نمیکند
@sahar-shafiee

2022-06-16 05:33 UTC, sahar-shafiee commented on redux/actions/cart/_reduceProduct.jsx
> +      if (count == 1) {
@milad7212 بله خطایی ایجاد نمیکنه ولی بهتر همه جا از === استفاده بشه تا جلوی  خطا گرفته بشه

2022-06-18 05:29 UTC, sahar-shafiee approved these changes

2022-06-18 05:34 UTC, merged