Change value of options to object of name and id
nakhll-company/nakhll_frontend pull request #149
Opened 2022-06-12 10:19 UTC by sahar-shafiee

2022-06-13 04:42 UTC, milad7212 requested changes

2022-06-13 04:42 UTC, milad7212 commented on pages/fp/store/create/index.jsx
> +      setStateData(await getStates());
getStates()
داخل این تابع ای پی ای در صورتی که بدرستی کال نشد بجای false یک ارایه خالی بفرستید . وهمچنین اگه استوس 200 نبود نیز یک ارایه خالی برگردانید

2022-06-13 04:42 UTC, milad7212 commented on pages/fp/store/create/index.jsx
> +              setCitiesData(await cities);
why do you use await cities?

2022-06-13 04:42 UTC, milad7212 commented on pages/fp/store/create/index.jsx
> +              const cities = await getCities(optionValue.id);
getCities
برگرداندن ارایه خالی در صورت شکست ای پی ای

2022-06-13 04:42 UTC, milad7212 commented on pages/fp/store/create/index.jsx
> +              setBigCitiesData(await bigCities);
No need to use await bigCities----->bigCities is enough

2022-06-14 04:22 UTC, sahar-shafiee commented
@milad7212 لطفا بررسی کنید

2022-06-14 04:52 UTC, milad7212 requested changes

2022-06-14 04:52 UTC, milad7212 commented on api/general/getBigCities.js
> +export const getBigCities = async (id) => {
این ادرس ای پی ای معتبر نمی باشد.
بودن try    هم ضریب اطمینان را بالاتر میبرد اگر باشد بهتر است

2022-06-14 04:52 UTC, milad7212 commented on api/general/getCities.js
> +export const getCities = async (id) => {
try {}catch

2022-06-14 04:52 UTC, milad7212 commented on pages/fp/store/create/index.jsx
> +  console.log("bigCitiesData >>>>>", bigCitiesData);
Please delete console

2022-06-14 06:31 UTC, sahar-shafiee commented on api/general/getBigCities.js
> +export const getBigCities = async (id) => {
@milad7212 
try{}catch
ضریب اطمینان چه چیزی رو بالاتر میبره
من جست و جو کردم و متوجه شدم در صورت نمایش خطا سمت فرانت بله میتونه کمک کننده باشه
ولی در اپ ما خطاها از سمت بک میان و فقط چک کردن استاتوس مد نظر ما می باشد
باز اگر رفرنسی برای این مسئله دارین ممنون میشم بفرستین تا مطالعه کنم

2022-06-14 06:34 UTC, milad7212 commented on api/general/getBigCities.js
> +export const getBigCities = async (id) => {
در تغییرات برنامه نویس بعدی در این خطوط در صورت خطای برنامه اگه ارور داشته باشد منجر به کرش شدنش نمیشود.

2022-06-14 06:36 UTC, sahar-shafiee commented on api/general/getBigCities.js
> +export const getBigCities = async (id) => {
@milad7212 در صورتی که ای پی ای با خطا مواجه شود که ارور نمایش داده می شود
لطفا روند ایجاد خطا رو شفاف تر توضیح بدین یا مثال بزنید تا من بهتر متوجه منظور شما بشم

2022-06-14 06:37 UTC, milad7212 commented on api/general/getBigCities.js
> +export const getBigCities = async (id) => {
کار مباحی بود .اگه دیدید دوست دارید اضافه بفرمایید :)

2022-06-14 09:59 UTC, milad7212 approved these changes

2022-06-16 05:21 UTC, sahar-shafiee commented on api/general/getBigCities.js
> +export const getBigCities = async (id) => {
@milad7212 بی زحمت گر کد مسئله دیگه ای نداره پول ریکوئست را تایید کنید

2022-06-16 07:57 UTC, milad7212 approved these changes

2022-06-18 05:18 UTC, merged